Repository LunarG/VulkanTools, pull requests merged in 2020-08, with the labels that each got.

#1083 vkconfig: Fixed several post SDK issues
  vkconfig/configurator.cpp
  vkconfig/configurator.h
  vkconfig/dlgcustompaths.cpp
  vkconfig/dlgprofileeditor.cpp
  vkconfig/mainwindow.cpp
  vkconfig/mainwindow.h
Labels: Project - vkconfig

#1105 vkconfig: .pro file fix and description editiong
  vkconfig/dlgprofileeditor.cpp
  vkconfig/dlgprofileeditor.ui
  vkconfig/vkconfig.pro
Labels: P3, bug

#1110 vkconfig: add changelog and build version
  vkconfig/CHANGELOG.md
  vkconfig/configurator.h
  vkconfig/mainwindow.cpp
  vkconfig_core/version.h
Labels: P2, enhancement

#1112 vkconfig: Improve default applications handling
  vkconfig/configurator.cpp
  vkconfig/configurator.h
  vkconfig/dlgcreateassociation.cpp
  vkconfig/dlgcreateassociation.ui
  vkconfig/mainwindow.cpp
  vkconfig_core/layer_type.cpp
Labels: P2, enhancement

#1113 vkconfig: Filter out VK_DBG_LAYER_ACTION_DEBUG_OUTPUT on Linux and macOS #1086
  vkconfig/configurator.cpp
  vkconfig/dlgvulkananalysis.cpp
  vkconfig/dlgvulkaninfo.cpp
  vkconfig/mainwindow.cpp
  vkconfig_core/layer.cpp
  vkconfig_core/path_manager.cpp
  vkconfig_core/platform.h
Labels: P2, bug
