Repository LunarG/VulkanTools, pull requests merged in 2020-09, with the labels that each got.

#1119 vkconfig: multiple debug actions simultaneously
  vkconfig/mainwindow.cpp
  vkconfig/settingstreemanager.cpp
  vkconfig/settingstreemanager.h
  vkconfig_core/layer_setting.cpp
  vkconfig_core/version.h
Labels: P1, enhancement

#1126 vkconfig: Indicate the version for which gfxrecon requires a different prefix
  vkconfig/configurator.cpp
Labels: P2, enhancement

#1127 vkconfig: Fix custon path #1122
  vkconfig/dlgprofileeditor.cpp
  vkconfig_core/configuration.cpp
  vkconfig_core/configuration.h
Labels: P0 - Must Fix, bug

#1129 vkconfig: Better express the behavior of implicit layers #1124
  vkconfig/dlgprofileeditor.cpp
Labels: P2, enhancement

#1128 vkconfig: Fix asserts on environment that ran old dev versions
  vkconfig_core/environment.cpp
Labels: P0 - Must Fix, bug, enhancement

#1133 vkconfig: Mode to discard shader based configurations and presets #1130
  vkconfig/configurator.cpp
  vkconfig/khronossettingsadvanced.cpp
  vkconfig/mainwindow.cpp
  vkconfig/settingstreemanager.cpp
  vkconfig/settingstreemanager.h
  vkconfig_core/configuration.cpp
  vkconfig_core/platform.h
Labels: OS - Linux, OS - macOS, P0 - Must Fix, bug

#1141 vkconfig: Fix assert because only Windows has executable suffix #1138
  vkconfig_core/path_manager.cpp
Labels: OS - Linux, OS - macOS, P1, bug

#1142 vkconfig: Fix assert when the applist.json file was deleted #1136
  vkconfig_core/environment.cpp
Labels: OS - Linux, OS - macOS, P3, bug

#1146 vkconfig: Add layers configuration tests
  vkconfig/configurator.cpp
  vkconfig/resourcefiles/vkconfig.aps
  vkconfig/settingstreemanager.cpp
  vkconfig_core/configuration.cpp
  vkconfig_core/configuration.h
  vkconfig_core/test/CMakeLists.txt
  vkconfig_core/test/Configuration 2.0.1 - API dump.json
  vkconfig_core/test/Configuration 2.0.1 - Best Practices.json
  vkconfig_core/test/Configuration 2.0.1 - Frame Capture.json
  vkconfig_core/test/Configuration 2.0.1 - GPU-Assisted.json
  vkconfig_core/test/Configuration 2.0.1 - Shader Printf.json
  vkconfig_core/test/Configuration 2.0.1 - Standard.json
  vkconfig_core/test/Configuration 2.0.2 - Best Practices.json
  vkconfig_core/test/Configuration 2.0.2 - Debug Printf.json
  vkconfig_core/test/Configuration 2.0.2 - Exclude all layers.json
  vkconfig_core/test/Configuration 2.0.2 - Frame Capture.json
  vkconfig_core/test/Configuration 2.0.2 - GPU-Assisted.json
  vkconfig_core/test/Configuration 2.0.2 - Override all layers.json
  vkconfig_core/test/Configuration 2.0.2 - Standard.json
  vkconfig_core/test/resources.qrc
  vkconfig_core/test/test_configuration.cpp
  vkconfig_core/test/test_configuration_manager.cpp
  vkconfig_core/test/test_layer_type.cpp
  vkconfig_core/test/test_vulkan.cpp
Labels: P1, enhancement

#1147 vkconfig: Fix configuration renaming #1144
  vkconfig/alert.cpp
  vkconfig/alert.h
  vkconfig/dlgprofileeditor.cpp
  vkconfig/mainwindow.cpp
  vkconfig/vkconfig.pro
Labels: P0 - Must Fix, bug

#1149 vkconfig: Clear log on launch enabled by default #1143
  vkconfig/mainwindow.cpp
  vkconfig_core/environment.h
Labels: P3, bug, enhancement

#1148 vkconfig: Fix exit notification not being saved
  vkconfig_core/environment.cpp
Labels: P0 - Must Fix, bug

#1154 vkconfig: Fix no setting when switch between exclude and override #1150
  vkconfig/configurator.cpp
  vkconfig/configurator.h
  vkconfig/dlgprofileeditor.cpp
  vkconfig_core/configuration.cpp
Labels: P0 - Must Fix, bug

#1155 vkconfig: Fix for some macOS regressions
  vkconfig/dlgcreateassociation.cpp
  vkconfig_core/path_manager.cpp
Labels: P0 - Must Fix, bug

#1157 vkconfig: Fix application list always disabled #1153
  vkconfig/dlgcreateassociation.cpp
Labels: P0 - Must Fix, bug

#1161 Fix gui update issue on macOS
  vkconfig/dlgprofileeditor.cpp
Labels: OS - macOS, bug

#1163 vkconfig: Fix layers window reset button #1162
  vkconfig/configurator.cpp
  vkconfig/configurator.h
  vkconfig/dlgprofileeditor.cpp
  vkconfig/dlgprofileeditor.h
Labels: P2, bug

#1167 vkconfig: Don't reset systematically settings
  vkconfig/configurator.cpp
  vkconfig/dlgprofileeditor.cpp
  vkconfig/dlgprofileeditor.h
  vkconfig/mainwindow.cpp
Labels: P0 - Must Fix, bug

#1170 vkconfig: Fix the display of numeric bool #1166
  vkconfig/widget_bool_setting.cpp
Labels: P0 - Must Fix, Project - vkconfig, bug

#1171 vkconfig: Search vkcube at the package install path #1088
  vkconfig_core/environment.cpp
Labels: OS - Linux, P1, Project - vkconfig, bug

#1177 vkconfig: Reenabled Vulkan status
  vkconfig/vulkan.cpp
Labels: P0 - Must Fix, bug

#1180 vkconfig: Mac regression fixes
  vkconfig/dlgcreateassociation.cpp
  vkconfig/dlgvulkananalysis.cpp
Labels: OS - macOS, P2, Project - vkconfig, bug

#1181 vkconfig: manual ordering of overridden layers
  vkconfig/CHANGELOG.md
  vkconfig/configurator.cpp
  vkconfig/configurator.h
  vkconfig/dlgprofileeditor.cpp
  vkconfig/dlgprofileeditor.h
  vkconfig/dlgprofileeditor.ui
  vkconfig/mainwindow.cpp
  vkconfig/vkconfig.md
  vkconfig_core/configuration.cpp
  vkconfig_core/environment.cpp
  vkconfig_core/environment.h
  vkconfig_core/layer_setting.cpp
  vkconfig_core/layer_setting.h
Labels: P1, bug

#1187 vkconfig: Fix Capture Frame Range configuration #1184 #1185
  vkconfig/configurator.cpp
  vkconfig/resourcefiles/Frame Capture - Range (F5 to start and to stop).json
  vkconfig/resources.qrc
  vkconfig_core/test/Configuration 2.0.2 - Frame Capture.json
  vkconfig_core/test/test_configuration.cpp
Labels: P2, bug

#1190 vkconfig: Fix crash when no configuration is actived
  vkconfig/configurator.cpp
Labels: P0 - Must Fix, bug

#1182 devsim: Add emulation for portability extension
  layersvt/VkLayer_device_simulation.json.in
  layersvt/device_simulation.cpp
  layersvt/device_simulation.md
  layersvt/device_simulation_examples/portability_test.json
Labels: enhancement

#1194 vkconfig: Fix ParameterRank
  vkconfig/dlgprofileeditor.cpp
Labels: P2, bug

#1195 devsim: Fix manifest JSON file
  layersvt/VkLayer_device_simulation.json.in
Labels: bug

#1197 macOS fixes for cmake builds
  vkconfig/macOS/vkconfig.cmake
  vkconfig/vkconfig.pro
  vkconfig_core/CMakeLists.txt
Labels: OS - macOS, P0 - Must Fix, bug

#1196 devsim: Fix conversion warnings
  layersvt/device_simulation.cpp
Labels: OS - Windows, bug

#1200 vkconfig: Fix terminate of hang launched application
  vkconfig/mainwindow.cpp
  vkconfig/mainwindow.h
Labels: P3, Project - vkconfig, bug, enhancement

#1191 vkconfig: Improve the management of tool home directories
  vkconfig/configurator.cpp
  vkconfig/configurator.h
  vkconfig/mainwindow.cpp
  vkconfig_core/configuration.cpp
  vkconfig_core/path_manager.cpp
  vkconfig_core/path_manager.h
Labels: P3, enhancement
