Repository LunarG/VulkanTools, pull requests merged in 2020-11, with the labels that each got.

#1222 vkconfig: Make sure there isn't no configuration #1221
  vkconfig/configurator.cpp
  vkconfig/test/test_util.cpp
Labels: bug

#1225 vkconfig: Fix layers override update when changing layers management options
  vkconfig/CHANGELOG.md
  vkconfig/configurator.cpp
  vkconfig/configurator.h
  vkconfig/mainwindow.cpp
  vkconfig/settingstreemanager.cpp
Labels: P1, bug, enhancement

#1226 vkconfig: Fix manual ordering of layers #1214
  vkconfig/CHANGELOG.md
  vkconfig/configurator.cpp
  vkconfig/dialog_layers.cpp
  vkconfig/test/test_util.cpp
  vkconfig_core/configuration.cpp
  vkconfig_core/parameter.cpp
Labels: P0 - Must Fix, Project - vkconfig, bug

#1230 vkconfig: Fix warning about old loader when trying to use application list
  vkconfig/CHANGELOG.md
  vkconfig/configurator.cpp
  vkconfig/configurator.h
  vkconfig/mainwindow.cpp
  vkconfig/mainwindow.h
Labels: P1, bug

#1231 vkconfig: Follow community convention for readme file name
  BUILD.md
  README.md
  vkconfig/README.md
  vkconfig/resources.qrc
  vkconfig/settingstreemanager.cpp
  vkconfig_core/test/test_layer_manager.cpp
  vkconfig_core/test/test_util.cpp
  vkconfig_core/test/test_version.cpp
  vkconfig_core/util.cpp
  vkconfig_core/version.h
Labels: enhancement

#1238 vkconfig: fix warning
  vkconfig/settingstreemanager.cpp
  vkconfig_core/environment.cpp
  vkconfig_core/environment.h
Labels: P3, bug

#1240 C.I.: Improve build platform coverage
  .appveyor.yml
  vkconfig/CHANGELOG.md
  vkconfig/main_layers.cpp
  vkconfig/mainwindow.cpp
  vkconfig/vkconfig.pro
  vkconfig_core/environment.cpp
Labels: P1, enhancement

#1241 vkconfig: Make Version class easier to debug
  vkconfig_core/test/test_version.cpp
  vkconfig_core/version.cpp
  vkconfig_core/version.h
Labels: P2, enhancement

#1243 C.I.: Multithreaded NMake build
  .appveyor.yml
Labels: P2, Project - vkconfig, enhancement

#1244 C.I.: Multiple threads cmake build in appveyor
  .appveyor.yml
Labels: P1, enhancement

#1245 C.I.: Only build with CMake XOR QMake
  .appveyor.yml
Labels: P2, enhancement

#1248 vkconfig: Fix QtCreator build on OSX
  vkconfig/vkconfig.pro
Labels: OS - macOS, bug

#1249 vkconfig: Fix initialization of added applications on macOS
  vkconfig/CHANGELOG.md
  vkconfig/dialog_applications.cpp
  vkconfig/dialog_applications.h
  vkconfig/vkconfig.pro
  vkconfig_core/environment.cpp
  vkconfig_core/environment.h
  vkconfig_core/override.cpp
Labels: OS - macOS, OS - platform independent, P1, bug

#1250 vkconfig: Fix broken link, use python3 to build
  BUILD.md
Labels: OS - platform independent, P2, Project - vkconfig, bug
