Repository LunarG/VulkanTools, pull requests merged in 2021-06, with the labels that each got.

#1522 vkconfig: add validation shader caching UI
  vkconfig/CHANGELOG.md
  vkconfig/settings_validation_areas.cpp
  vkconfig/settings_validation_areas.h
Labels: OS - platform independent, P1, Project - vkconfig, enhancement

#1524 docs: Add list of sample configs to DevSim docs.
  layersvt/device_simulation.md
Labels: Project - devsim, documentation

#1536 devsim: macOS doesn't support Vulkan 1.2
  layersvt/VkLayer_device_simulation.json.in
Labels: OS - macOS, P1, Project - devsim, bug, enhancement

#1537 devsim: add desktop portability devsim config files
  layersvt/VkLayer_device_simulation.json.in
  layersvt/device_simulation_examples/sdk_sample_configs/portability_desktop_1_0.json
  layersvt/device_simulation_examples/sdk_sample_configs/portability_desktop_1_2.json
Labels: OS - Linux, OS - Windows, OS - macOS, P1, Project - devsim, enhancement

#1541 devsim: first step to be able to read GPUinfo database
  layersvt/device_simulation.cpp
Labels: OS - platform independent, P1, Project - devsim, enhancement

#1535 devsim: Add combination modes for format props
  layersvt/VkLayer_device_simulation.json.in
  layersvt/device_simulation.cpp
  layersvt/device_simulation.md
Labels: Project - devsim, documentation, enhancement

#1539 devsim: Fix minimum devsim config file issues
  layersvt/device_simulation_examples/sdk_sample_configs/portability_minimum_vulkan_1_0.json
  layersvt/device_simulation_examples/sdk_sample_configs/portability_minimum_vulkan_1_1.json
  layersvt/device_simulation_examples/sdk_sample_configs/portability_minimum_vulkan_1_2.json
  layersvt/device_simulation_examples/sdk_sample_configs/spec_minimum_vulkan_1_0.json
  layersvt/device_simulation_examples/sdk_sample_configs/spec_minimum_vulkan_1_1.json
  layersvt/device_simulation_examples/sdk_sample_configs/spec_minimum_vulkan_1_2.json
Labels: Project - devsim, bug

#1553 devsim: Add surface capabilities modifications
  layersvt/VkLayer_device_simulation.json.in
  layersvt/device_simulation.cpp
  layersvt/device_simulation.md
Labels: Project - devsim, documentation, enhancement

#1555 vkconfig: fix shader cache setting key
  vkconfig/settings_validation_areas.cpp
Labels: OS - platform independent, P1, Project - vkconfig, bug

#1556 devsim: Update minimum portability subset configs
  layersvt/device_simulation_examples/sdk_sample_configs/portability_minimum_vulkan_1_0.json
  layersvt/device_simulation_examples/sdk_sample_configs/portability_minimum_vulkan_1_1.json
  layersvt/device_simulation_examples/sdk_sample_configs/portability_minimum_vulkan_1_2.json
Labels: P1, Project - devsim

#1558 devsim: Fix layer extension list replacement
  layersvt/device_simulation.cpp
Labels: P1, Project - devsim, bug

#1559 devsim: Fix AndroidGetEnv use after free error
  layersvt/device_simulation.cpp
Labels: P0, Project - devsim, bug

#1562 vkconfig: Fix upgrade of 'vkcube' path when the path is no longer valid
  vkconfig/CHANGELOG.md
  vkconfig_core/environment.cpp
Labels: OS - Linux, OS - macOS, P2, Project - vkconfig, bug

#1563 devsim: Fix Surface Capabilities
  layersvt/device_simulation.cpp
Labels: P0, Project - devsim, bug

#1566 vkconfig: clean up, there is no local/global here
  vkconfig/vulkan.cpp
Labels: OS - platform independent, P3, Project - vkconfig, enhancement

#1567 vkconfig: fix crash when renaming a configuration #1551
  vkconfig/mainwindow.cpp
  vkconfig/mainwindow.h
Labels: OS - platform independent, P1, Project - vkconfig, bug

#1568 vkconfig: Remove Qt Warning on Qt 5.11 and older
  vkconfig/widget_setting_list.cpp
  vkconfig/widget_setting_list.h
Labels: OS - platform independent, P3, Project - vkconfig, bug

#1569 vkconfig: add build date in the title bar
  vkconfig/CHANGELOG.md
  vkconfig/mainwindow.cpp
  vkconfig/vkconfig.pro
  vkconfig_core/date.cpp
  vkconfig_core/date.h
  vkconfig_core/test/CMakeLists.txt
  vkconfig_core/test/test_date.cpp
Labels: OS - platform independent, P2, Project - vkconfig, enhancement
