Repository LunarG/VulkanTools, pull requests merged in 2022-02, with the labels that each got.

#1638 vkconfig: add check of the api-version and layer version
  vkconfig/dialog_custom_paths.cpp
  vkconfig/dialog_layers.cpp
  vkconfig_core/alert.cpp
  vkconfig_core/alert.h
  vkconfig_core/configuration_manager.cpp
  vkconfig_core/configuration_manager.h
Labels: enhancement, P2, Project - vkconfig, OS - platform independent

#1641 vkconfig: always add all layers paths to override_paths
  vkconfig_core/override.cpp
  vkconfig_core/test/override_layers_2_2_2_schema_1_2_1.json
Labels: bug, P1, OS - platform independent

#1642 Vkconfig fix for VULKAN_SDK set on macOS
  vkconfig_core/path.cpp
Labels: bug, P1, OS - macOS

#1643 vkconfig: fix creating a new configuration crash
  vkconfig/dialog_layers.cpp
Labels: bug, P0, OS - platform independent

#1644 ${VP_DEFAULT} is the default value for the profiles layer
  vkconfig/widget_setting_enum.cpp
  vkconfig_core/parameter.cpp
Labels: bug, P0, OS - platform independent

#1648 vkconfig: system paths are added last in override_paths
  vkconfig_core/override.cpp
Labels: bug, Project - vkconfig, P0, OS - platform independent

#1654 vkconfig: add doc changelog
  vkconfig/CHANGELOG.md
Labels: P2, OS - platform independent, documentation
