Repository LunarG/VulkanTools, pull requests merged in 2023-11, with the labels that each got.

#1919 cmake: Only require the CXX compiler
  CMakeLists.txt
Labels: build

#1920 cmake: Cleanup scripts
  CMakeLists.txt
  layersvt/CMakeLists.txt
  tests/CMakeLists.txt
  via/CMakeLists.txt
Labels: build

#1929 Add iOS build to CI
  .github/workflows/ci.yml
  CMakeLists.txt
  layersvt/CMakeLists.txt
  layersvt/api_dump.h
Labels: build

#1934 Fix vkvia regression
  scripts/known_good.json
  via/CMakeLists.txt
Labels: bug, build

#1937 vkconfig: Fix doc generator, no need for env name, it's generated
  vkconfig_core/setting.cpp
  vkconfig_core/test/test_layer.cpp
Labels: enhancement, P2, OS - platform independent

#1939 Cleanup layer CMake code
  layersvt/CMakeLists.txt
Labels: build
