Repository LunarG/VulkanTools, pull requests merged in 2024-07, with the labels that each got.

#2050 layers: Run tests on C.I.
  .github/workflows/ci.yml
  CMakeLists.txt
  layersvt/CMakeLists.txt
  scripts/github_ci_linux.py
Labels: OS - platform independent

#2057 VkConfig: Fix tray combo-box signal method
  vkconfig/mainwindow.cpp
  vkconfig/mainwindow.h
  vkconfig3/mainwindow.cpp
  vkconfig3/mainwindow.h
Labels: bug, Project - vkconfig, P0 - Must Fix, OS - platform independent

#2067 vkconfig: Fix user-path duplication on reset
  vkconfig_core/configuration.cpp
Labels: bug, P3, Project - vkconfig, OS - platform independent

#2071 Update Crash Diagnostic.json
  vkconfig_core/configurations/2.2.2/Crash Diagnostic.json
Labels: bug, Project - vkconfig, OS - Apple, P0 - Must Fix

#2074 vkconfig3: Improve SDK upgrade
  vkconfig_core/configurations/3.0.0/Crash Diagnostic.json
  vkconfig_core/environment.cpp
  vkconfig_gui/configuration_layer_widget.cpp
  vkconfig_gui/mainwindow.cpp
Labels: enhancement, P1, OS - platform independent

#2077 vkconfig3: Full ordering of layers
  vkconfig_core/configurator.cpp
  vkconfig_core/parameter.cpp
  vkconfig_core/type_layer_control.cpp
  vkconfig_core/type_layer_control.h
  vkconfig_gui/configuration_layer_widget.cpp
  vkconfig_gui/mainwindow.cpp
  vkconfig_gui/mainwindow.ui
Labels: enhancement, P1, OS - platform independent

#2078 Vkconfig3 ordering layers
  vkconfig_core/configuration.cpp
  vkconfig_core/configuration.h
  vkconfig_core/configurator.cpp
  vkconfig_core/parameter.cpp
  vkconfig_core/test/test_configuration_built_in.cpp
  vkconfig_gui/configuration_layer_widget.cpp
  vkconfig_gui/mainwindow.cpp
  vkconfig_gui/mainwindow.h
  vkconfig_gui/settings_tree.cpp
Labels: enhancement, P1, OS - platform independent

#2080 vkconfig3: Configuration tab UI
  vkconfig_core/configuration.cpp
  vkconfig_core/configuration.h
  vkconfig_core/configurator.cpp
  vkconfig_core/environment.h
  vkconfig_core/test/test_configuration.cpp
  vkconfig_core/type_layer_control.cpp
  vkconfig_core/type_layer_control.h
  vkconfig_gui/configuration_layer_widget.cpp
  vkconfig_gui/configuration_layer_widget.h
  vkconfig_gui/mainwindow.cpp
  vkconfig_gui/mainwindow.h
  vkconfig_gui/mainwindow.ui
  vkconfig_gui/settings_tree.cpp
  vkconfig_gui/settings_tree.h
Labels: enhancement, P1, OS - platform independent, Project - vkconfig3

#2083 vkconfig3: Add settings tree state load and store
  vkconfig_core/configuration.cpp
  vkconfig_core/configuration.h
  vkconfig_core/parameter.h
  vkconfig_core/test/test_configuration.cpp
  vkconfig_core/test/test_configuration_built_in.cpp
  vkconfig_gui/mainwindow.cpp
  vkconfig_gui/mainwindow.ui
  vkconfig_gui/settings_tree.cpp
  vkconfig_gui/settings_tree.h
Labels: enhancement, P1, OS - platform independent, Project - vkconfig3

#2084 vkconfig3: Add layers configuration context menu
  vkconfig_core/configuration.h
  vkconfig_core/test/CMakeLists.txt
  vkconfig_core/test/test_ui.cpp
  vkconfig_core/ui.cpp
  vkconfig_core/ui.h
  vkconfig_gui/mainwindow.cpp
  vkconfig_gui/mainwindow.h
  vkconfig_gui/vkconfig.pro
Labels: enhancement, P1, OS - platform independent, test
